name: conecta
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0"

dependencies:
  adaptive_breakpoints: ^0.0.4
  adaptive_components: ^0.0.3
  adaptive_navigation: ^0.0.5

  asuka: ^2.0.0+1

  cached_network_image: ^3.2.1
  collection: ^1.15.0

  cupertino_icons: ^1.0.4

  dio: ^4.0.6
  dynamic_color: ^1.2.2

  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.4

  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  flutter_modular: ^5.0.3
  flutter_native_splash: ^2.2.3+1
  flutter_native_timezone: ^2.0.0
  flutter_triple: ^1.2.7+2
  fpdart: ^0.0.14
  google_fonts: ^2.3.3
  # hive: ^2.2.2
  # hive_flutter: ^1.1.0
  hydrated_triple: ^0.0.3
  intl: ^0.17.0
  markdown: ^5.0.0
  markdown_editable_textinput: ^2.0.2
  material_color_utilities: ^0.1.4
  modular_triple_bind: ^1.0.0
  path_provider: ^2.0.10
  rxdart: ^0.27.3
  shared_preferences: ^2.0.15
  shared_preferences_android: ^2.0.12
  timezone: ^0.8.0
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.1.11
  # hive_generator: ^1.1.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  modular_test: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  color_dark: "#121212"
  image_dark: assets/images/splash_dark.png
  android: true
  android_gravity: center
